
# create documentation in the form of a .txt file called "metadata"

sink(paste(pathway, "metadata.txt"))
cat("Additional information: Same as run 25 but without noise in data.\n") 
cat("Version: "); cat(version, sep = "\n")
cat("Number of Species = "); cat(n_spec, sep="\n")
cat("Number of Clusters = "); cat(n_clust, sep="\n")
cat("Cluster Assignments:"); for (i in 1:n_clust) {cat(paste(" Cluster ", i, ": ", sep = "")); cat(cl[[i]])}; cat("\n")
cat("Total time = "); cat(time, sep="\n")
cat("Time step = "); cat(dt, sep="\n")
cat("Number of time points = "); cat(time/dt, sep="\n")
cat("seed = "); cat(seed, sep="\n")
cat("Growth Rates = "); cat(b); cat("\n")
cat("Initial Abundances = "); cat(y); cat("\n")
cat("Interaction Matrix = ", sep="\n")
print(cl_int)
cat("Self-Interactions = ", sep="\n")
print(sf_int)
cat("nu_a = "); cat(nu_a, sep="\n")
cat("nu_b = "); cat(nu_b, sep="\n")
cat("nu_w = "); cat(nu_w, sep="\n")
cat("Number of iterations = "); cat(n_iter, sep="\n")
cat("Number of chains = "); cat(n_chains, sep="\n")
cat("Distance between true and inferred cluster interaction matrices = "); cat(cl_dist, sep="\n")
sink()
